name: journal_club
channels:
  - conda-forge
dependencies:
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.12.14
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - idna=3.10
  - libcxx=19.1.7
  - libexpat=2.6.4
  - libffi=3.4.2
  - liblzma=5.6.3
  - libmpdec=4.0.0
  - libsqlite=3.47.2
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.4.0
  - pip=24.3.1
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.13.1
  - python_abi=3.13
  - readline=8.2
  - requests=2.32.3
  - tk=8.6.13
  - tzdata=2024b
  - urllib3=2.3.0
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
    - PyPDF2==3.0.1
    - openai==1.59.7
    - tiktoken==0.8.0
